const QUESTIONS = [
  { question: "Choose the correct spelling:", options: ["Enviroment", "Environment", "Envirnment", "Enviornment"], correct: 1 },
  { question: "Select the synonym of 'Brave':", options: ["Coward", "Fearless", "Weak", "Lazy"], correct: 1 },
  { question: "Fill in the blank: She ___ to school every day.", options: ["go", "goes", "gone", "going"], correct: 1 },
  { question: "Antonym of 'Ancient' is:", options: ["Old", "Historic", "Modern", "Traditional"], correct: 2 },
  { question: "Choose the correct article: ___ apple a day keeps the doctor away.", options: ["A", "An", "The", "No article"], correct: 1 },
  { question: "Change into passive voice: He wrote a letter.", options: ["A letter was written by him", "He has written a letter", "A letter is written", "Writing was done"], correct: 0 },
  { question: "Choose the correct tense: They ___ their homework now.", options: ["do", "did", "are doing", "done"], correct: 2 },
  { question: "Identify the noun: 'Honesty is the best policy.'", options: ["Honesty", "is", "best", "policy"], correct: 0 },
  { question: "Synonym of 'Happy':", options: ["Sad", "Joyful", "Angry", "Tired"], correct: 1 },
  { question: "Antonym of 'Increase':", options: ["Grow", "Expand", "Reduce", "Rise"], correct: 2 },
  { question: "Choose the correct preposition: He is afraid ___ dogs.", options: ["to", "for", "of", "by"], correct: 2 },
  { question: "Which is correct?", options: ["He don't like tea", "He doesn't like tea", "He didn't likes tea", "He no like tea"], correct: 1 },
  { question: "Change into plural: 'Child'", options: ["Childs", "Children", "Childes", "Childrens"], correct: 1 },
  { question: "The opposite of 'Permanent' is:", options: ["Temporary", "Stable", "Constant", "Solid"], correct: 0 },
  { question: "Identify the adjective: 'The sky is blue.'", options: ["sky", "is", "blue", "the"], correct: 2 },
  { question: "Choose the correct form: 'She has ___ her work.'", options: ["finish", "finishes", "finished", "finishing"], correct: 2 },
  { question: "Choose the correct sentence:", options: ["I am agree", "I agrees", "I am agreed", "I agree"], correct: 3 },
  { question: "Meaning of 'Once in a blue moon':", options: ["Frequently", "Rarely", "Always", "Never"], correct: 1 },
  { question: "Correct the sentence: 'He is senior than me.'", options: ["He is senior to me", "He is senior from me", "He is senior with me", "He is senior by me"], correct: 0 },
  { question: "Choose correct question tag: 'You are coming, ___?'", options: ["aren’t you", "isn’t you", "don’t you", "won’t you"], correct: 0 }
];
