name: Parallel Headless Browser

on:
  workflow_dispatch:    # run manually
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Selenium + Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install selenium

      - name: Run script
        env:
          PATH: /usr/lib/chromium-browser/:$PATH
        run: python main.py
